repos:
  - repo: local
    hooks:
      - id: mvn-checkstyle
        name: Runs Maven checkstyle
        entry: python scripts/pre-commit/checkstyle.py
        language: python
        verbose: true
        files: \.(java)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line endings by the UNIX 'lf' character.

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        args:
          - -i
          - --max-line-length=90
          - --ignore=E402
        files: \.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8  # latest stable as of Oct 2025
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: \.py$
