/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */
package org.dspace.app.rest.repository.patch.operation;

import java.sql.SQLException;

import org.apache.commons.lang3.BooleanUtils;
import org.dspace.app.rest.exception.DSpaceBadRequestException;
import org.dspace.app.rest.model.patch.Operation;
import org.dspace.authorize.AuthorizeException;
import org.dspace.content.DCDate;
import org.dspace.content.Item;
import org.dspace.content.MetadataSchemaEnum;
import org.dspace.content.service.InstallItemService;
import org.dspace.content.service.ItemService;
import org.dspace.core.Context;
import org.dspace.eperson.EPerson;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Base class for all resource patch operations.
 */
public abstract class PatchOperation<M> {

    // All PATCH operations' string (in operation.getOp())
    public static final String OPERATION_REPLACE = "replace";
    public static final String OPERATION_ADD = "add";
    public static final String OPERATION_COPY = "copy";
    public static final String OPERATION_MOVE = "move";
    public static final String OPERATION_REMOVE = "remove";

    @Autowired
    InstallItemService installItemService;

    @Autowired
    ItemService itemService;

    /**
     * Updates the rest model by applying the patch operation.
     *
     * @param context   context of patch operation
     * @param resource  the dso.
     * @param operation the patch operation.
     * @return the patched dso
     * @throws DSpaceBadRequestException
     */
    public abstract M perform(Context context, M resource, Operation operation) throws SQLException;

    /**
     * Throws PatchBadRequestException for missing operation value.
     *
     * @param value
     *            the value to test
     */
    public void checkOperationValue(Object value) {
        if (value == null) {
            throw new DSpaceBadRequestException("No value provided for the operation.");
        }
        if (value instanceof String && (((String) value).trim().isBlank())) {
            throw new DSpaceBadRequestException("Value can't be empty or just spaces.");
        }
    }

    /**
     * Allows clients to use either a boolean or a string representation of boolean value.
     *
     * @param value the operation value
     * @return the original or derived boolean value
     * @throws DSpaceBadRequestException
     */
    Boolean getBooleanOperationValue(Object value) {
        Boolean bool;

        if (value instanceof String) {
            bool = BooleanUtils.toBooleanObject((String) value);
            if (bool == null) {
                // make sure the string was converted to boolean.
                throw new DSpaceBadRequestException("Boolean value not provided.");
            }
        } else {
            bool = (Boolean) value;
        }
        return bool;
    }

    /**
     * Adds provenance metadata to an item, documenting an action taken on the item.
     * This method logs the user who performed the action, the action description,
     * and the timestamp when the action occurred. It also appends a bitstream provenance
     * message generated by the InstallItemService.
     *
     * @param context the current DSpace context, which provides details about the current user
     *                and authorization information.
     * @param item    the DSpace item to which the provenance metadata should be added.
     * @param msg     a custom message describing the action taken on the item.
     * @throws SQLException         if there is a database access error while updating the item.
     * @throws AuthorizeException   if the current user is not authorized to add metadata to the item.
     */
    protected void addProvenanceMetadata(Context context, Item item, String msg)
            throws SQLException, AuthorizeException {
        String timestamp = DCDate.getCurrent().toString();
        EPerson e = context.getCurrentUser();
        StringBuilder prov = new StringBuilder();
        prov.append("Item ").append(msg).append(" by ")
                .append(e.getFullName()).append(" (").append(e.getEmail()).append(") on ")
                .append(timestamp).append("\n");
        prov.append(installItemService.getBitstreamProvenanceMessage(context, item));
        itemService.addMetadata(context, item, MetadataSchemaEnum.DC.getName(),
                "description", "provenance", "en", prov.toString());
        //Update item in DB
        itemService.update(context, item);
    }

    /**
     * Determines whether or not this Patch Operation can do this patch (Object of operation and path gets checked)
     * @param objectToMatch    Object whose class must be instance of type object
     *                              for which this PatchOperation was created
     * @param operation        Operation of the patch, should match this type of Patch Operation
     * @return                 True if this PatchOperation class can do the patch for this given dso type and Path
     */
    public abstract boolean supports(Object objectToMatch, Operation operation);

}
