#
# DSpace's reusable Docker build/push workflow.
#
# This is used by docker.yml for all Docker image builds
name: Reusable DSpace Docker Build

on:
  workflow_call:
    # Possible Inputs to this reusable job
    inputs:
      python_version_script_dest:
        required: false
        default: version.txt
        type: string
      run_python_version_script:
        required: false
        default: false
        type: boolean
      # Build name/id for this Docker build. Used for digest storage to avoid digest overlap between builds.
      build_id:
        required: true
        type: string
      # Requires the image name to build (e.g dspace/dspace-test)
      image_name:
        required: true
        type: string
      # Optionally the path to the Dockerfile to use for the build. (Default is [dockerfile_context]/Dockerfile)
      dockerfile_path:
        required: false
        type: string
      # Optionally the context directory to build the Dockerfile within. Defaults to "." (current directory)
      dockerfile_context:
        required: false
        type: string
        default: '.'
      # Optionally a list of "additional_contexts" to pass to Dockerfile. Defaults to empty
      dockerfile_additional_contexts:
        required: false
        type: string
        default: ''
      # If Docker image should have additional tag flavor details (e.g. a suffix), it may be passed in.
      tags_flavor:
        required: false
        type: string
    secrets:
      # Requires that Docker login info be passed in as secrets.
      DOCKER_USERNAME:
        required: true
      DOCKER_ACCESS_TOKEN:
        required: true
      # These URL secrets are optional. When specified & branch checks match, the redeployment code below will trigger.
      # Therefore builds which need to trigger redeployment MUST specify these URLs. All others should leave them empty.
      REDEPLOY_SANDBOX_URL:
        required: false
      REDEPLOY_DEMO_URL:
        required: false

# Define shared default settings as environment variables
env:
  IMAGE_NAME: ${{ inputs.image_name }}
  # Define tags to use for Docker images based on Git tags/branches (for docker/metadata-action)
  # For a new commit on default branch (main), use the literal tag 'latest' on Docker image.
  # For a new commit on other branches, use the branch name as the tag for Docker image.
  # For a new tag, copy that tag name as the tag for Docker image.
  # For a pull request, use the name of the base branch that the PR was created against or "latest" (for main).
  #   e.g. PR against 'main' will use "latest". a PR against 'dspace-7_x' will use 'dspace-7_x'.
  IMAGE_TAGS: |
    type=raw,value=latest,enable=${{ github.ref_name == github.event.repository.default_branch }}
    type=raw,value=${{ github.sha }}
    type=ref,event=branch,enable=${{ github.ref_name != github.event.repository.default_branch }}
    type=ref,event=tag
  # Define default tag "flavor" for docker/metadata-action per
  # https://github.com/docker/metadata-action#flavor-input
  # We manage the 'latest' tag ourselves to the 'main' branch (see settings above)
  TAGS_FLAVOR: |
    latest=false
    ${{ inputs.tags_flavor }}
  # When these URL variables are specified & required branch matches, then the sandbox or demo site will be redeployed.
  # See "Redeploy" steps below for more details.
  REDEPLOY_SANDBOX_URL: ${{ secrets.REDEPLOY_SANDBOX_URL }}
  REDEPLOY_DEMO_URL: ${{ secrets.REDEPLOY_DEMO_URL }}
  # Current DSpace branches (and architecture) which are deployed to demo.dspace.org & sandbox.dspace.org respectively
  DEPLOY_DEMO_BRANCH: 'dspace-8_x'
  DEPLOY_SANDBOX_BRANCH: 'main'
  DEPLOY_ARCH: 'linux/amd64'
  # Registry used during building of Docker images. (All images are later copied to docker.io registry)
  # We use GitHub's Container Registry to avoid aggressive rate limits at DockerHub.
  DOCKER_BUILD_REGISTRY: docker.io

jobs:
  docker-build:

    strategy:
      matrix:
        # Architectures / Platforms for which we will build Docker images
        # arch: [ 'linux/amd64', 'linux/arm64' ]
        arch: [ 'linux/amd64' ]
        os: [ ubuntu-latest ]
        isPr:
          - ${{ github.event_name == 'pull_request' }}
            # If this is a PR, we ONLY build for AMD64. For PRs we only do a sanity check test to ensure Docker builds work.
            # The below exclude therefore ensures we do NOT build ARM64 for PRs.
            # exclude:
            # - isPr: true
          # os: ubuntu-latest
          # arch: linux/arm64

    runs-on: ${{ matrix.os }}

    steps:
      # This step converts the slashes in the "arch" matrix values above into dashes & saves to env.ARCH_NAME
      # E.g. "linux/amd64" becomes "linux-amd64"
      # This is necessary because all upload artifacts CANNOT have special chars (like slashes)
      # NOTE: The regex-like syntax below is Bash Parameter Substitution
      - name: Prepare
        run: |
          platform=${{ matrix.arch }}
          echo "ARCH_NAME=${platform//\//-}" >> $GITHUB_ENV

      # https://github.com/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Add version
        if: ${{ inputs.run_python_version_script }}
        run: python scripts/sourceversion.py ${{ github.server_url }}/${{ github.repository }}/actions/runs/ ${{ github.run_id }} > ${{ inputs.python_version_script_dest }}


      # https://github.com/docker/login-action
      # NOTE: This login occurs for BOTH non-PRs or PRs. PRs *must* also login to access private images from GHCR
      # during the build process
      - name: Login to ${{ env.DOCKER_BUILD_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_BUILD_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/metadata-action
      # Extract metadata used for Docker images in all build steps below
      - name: Extract metadata (tags, labels) from GitHub for Docker image
        id: meta_build
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_BUILD_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          flavor: ${{ env.TAGS_FLAVOR }}

      #--------------------------------------------------------------------
      # First, for all branch commits (non-PRs) we build the image & upload
      # to GitHub Container Registry (GHCR). After uploading the image
      # to GHCR, we store the image digest in an artifact, so we can
      # create a merged manifest later (see 'docker-build_manifest' job).
      #
      # NOTE: We use GHCR in order to avoid aggressive rate limits at DockerHub.
      #--------------------------------------------------------------------
      # https://github.com/docker/build-push-action
      - name: Build and push image to ${{ env.DOCKER_BUILD_REGISTRY }}
        if: ${{ ! matrix.isPr }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          build-contexts: |
            ${{ inputs.dockerfile_additional_contexts }}
          context: ${{ inputs.dockerfile_context }}
          file: ${{ inputs.dockerfile_path }}
          # Tell DSpace's Docker files to use the build registry instead of DockerHub
          build-args:
            DOCKER_REGISTRY=${{ env.DOCKER_BUILD_REGISTRY }}
          platforms: ${{ matrix.arch }}
          push: true
          # Use tags / labels provided by 'docker/metadata-action' above
          tags: ${{ steps.meta_build.outputs.tags }}
          labels: ${{ steps.meta_build.outputs.labels }}
          # Use GitHub cache to load cached Docker images and cache the results of this build
          # This decreases the number of images we need to fetch from DockerHub
          cache-from: type=gha,scope=${{ inputs.build_id }}
          cache-to: type=gha,scope=${{ inputs.build_id }},mode=max
